project:
  # type: website
  type: manuscript
  title: "Energetic Particles"

website:
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd

manuscript:
  article: index.qmd
  code-links: [repo]

bibliography:
  - files/bibliography/research.bib

wrap: preserve

execute:
  eval: false

engines: [julia]
