project:
  type: website
  # type: manuscript
  title: "Energetic Particles"

website:
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd

manuscript:
  article: index.qmd

bibliography:
  - files/bibliography/research.bib

wrap: preserve

engines:
  - julia
