---
execute:
  eval: false
engine: julia
---


## Analysis

The total time between two consecutive current sheet encounters is modeled as the sum of the time spent inside the current sheet $T_{cs}$, and the time spent free-streaming between sheets $T_{fs}$, given by:

$$
T = T_{cs} + T_{fs}, \quad T_{fs} = \frac{s_{fs}}{|v_{∥,1}|}
$$

where $v_{∥,0}$, $v_{∥,1}$ are the particle's changed parallel velocity before and after interacting with the current sheet, respectively.

In the absence of scattering, the particle would follow the field line and travel a distance:

$$
s_0 = |v_{∥,0}| \cdot T = |v_{∥,0}| \left( T_{cs} + \frac{s_{fs}}{|v_{∥,1}|} \right).
$$

However, when scattering occurs, the total distance traveled becomes:

$$
s = s_{cs}^* + \text{sign}\left(\frac{v_{∥,1}}{v_{∥,0}}\right) s_{fs} \approx \text{sign}\left(\frac{v_{∥,1}}{v_{∥,0}}\right) s_{fs}
$$

under the approximation that $s_{cs}^* << s_{fs}$, where $s_{cs}^*$ is the effective parallel distance the particle travels within the current sheet. The net displacement compared to the unperturbed case is then:

$$
Δ s_∥ = s - s_0 = s_{fs} \left(\text{sign}\left(\frac{v_{∥,1}}{v_{∥,0}}\right) - \frac{|v_{∥,0}|}{|v_{∥,1}|} \right) - |v_{∥,0}| T_{cs}
$$

$$
P(α) dα = d(\sin^2 α)
=> P(α) = 2\sin α |\cos α|
$$

$$
<Δ s_∥> =  \int Δ s_∥ P(\mathbf{v}) dv^3 \sim \int_{0}^{\pi} Δ s_∥ P(α) \sin α dα \sim \int_{0}^{\pi} Δ s_∥ |\cos α| \sin^2 α dα
$$

Given $\mu=\cos α$, we have:
$$
\int_{0}^{\pi} Δ s_∥ |\cos α| \sin^2 α dα = \int_{-1}^{1} Δ s_∥ |\mu| \sqrt{1-\mu^2} d\mu
$$

For discrete samples $\mu_i$, we have:
$$
<Δ s_∥> =  \sum_i Δ s_{∥,i} |\mu_i| \sqrt{1-\mu_i^2} / \sum_i |\mu_i| \sqrt{1-\mu_i^2}
$$

where $N$ is the number of samples.


The parallel spatial diffusion coefficient is then expressed as:

$$
κ_∥ = \frac{(Δ s_∥)^2}{Δ t}
$$

Similarly, for the perpendicular direction:

$$
κ_\perp = \frac{(Δ s_\perp)^2}{T_{cs} + | s_{fs} / v_{∥,1} |}.
$$

The key parameters—$v_{∥,1}$, $T_{cs}$, $Δ s_\perp$, and $Δ t$—are directly extracted from test-particle simulations, while quantities such as the current sheet separation distance $s_{fs}$, thickness, shear angle, and normal orientation are treated as system parameters derived from solar wind observations. Together, these inputs enable a systematic and physically grounded estimation of spatial diffusion coefficients under realistic heliospheric conditions.

## Simulation


```{julia}
using CurrentSheetTestParticle
using CurrentSheetTestParticle: Vern9, DEFAULT_TSPAN
using CurrentSheetTestParticle: solve_param, ConstField, guiding_center, field_lines, solve_fl, field_lines_distance
using CurrentSheetTestParticle.Analysis
using TestParticleAnalysis: m, M
using DrWatson
using DataFrames, DataFramesMeta
using CairoMakie, AlgebraOfGraphics
using Beforerr

```

```{julia}
function run_sim(d; verbose=false)
    save_everystep = false
    diffeq = (; dtmax=1e-3)
    sols, (wϕs, B, u0s) = solve_params(RDProblemParams(; diffeq, d...); save_everystep, verbose)
    results = process_sols(sols, B, wϕs)
    results.v .= d[:v]
    results.θ .= d[:θ]
    results.β .= d[:β]
    d[:results] = results
    d
end

getaxis(ae::AxisEntries) = ae.axis
getaxis(p) = map(getaxis, p)
```

Normalized distance $s_{fs}/l_0$:

```{julia}
include("../src/utils.jl")

s_fs_n = let erg0 = 1u"MeV", s_fs = 4e2u"km/s" * 30u"minute", v′ = 8
    l0 = 3e3u"km"
    B0 = 10u"nT"
    t0 = Unitful.mp / (Unitful.q * B0) |> upreferred
    v0 = l0 / t0
    v = v0 * v′
    @info v energy(v)
    s_fs / l0 |> NoUnits
end
```

```{julia}
config = Dict(
    :θ => 60,
    :β => [0, 10, 30, 60],
    :v => 8,
    :init_kwargs => (; w=-0.8:0.1:0.8, Nϕ=128)
)
all_params = dict_list(config)
results = produce_or_load.(run_sim, all_params, datadir())
get_df(d) = d[1]["results"]
result = vcat(get_df.(results)...)

function process_perp!(result)
    @rtransform! result @astable begin
        :gc0 = guiding_center(:u0, :B)
        :gcf = guiding_center(:u1, :B)
        fl0_sol, flf_sol = field_lines(:gc0, :gcf, :B; tmax=1000 * :t1)
        dist = field_lines_distance(fl0_sol, flf_sol, :B)
        :fl0_sol = fl0_sol
        :s_cs = abs(fl0_sol.t[end])
        :Δs_perp = dist.dR_perp_asym
        :Δs_perp_min = dist.dR_perp_min
    end
end

# s_cs_fl(θ, β) = let 

# end

function process_free_stream!(result, s_fs)
    @rtransform! result @astable begin
        :s_fs = s_fs
        :v_para_0 = :v * :μ0
        :v_para_1 = :v * :μ1
        :Δt = :t1 + s_fs / abs(:v_para_1)
        :Δs_para = :s_cs + s_fs * (sign(:v_para_1 / :v_para_0) - abs(:v_para_0 / :v_para_1)) - abs(:v_para_0) * :t1
        :κ_para = (:Δs_para^2) / :Δt
        :κ_perp = (:Δs_perp^2) / :Δt
    end
end

@chain result begin
    process!
    process_perp!
    process_free_stream!(s_fs_n)
end
```

```{julia}
f = Figure()
let df = @subset result :β .== 60 :t1 .< DEFAULT_TSPAN[2]
    d = data(df)
    c = mapping(color=m.μ0_n)
    p1 = draw!(f[1, 1], d * c * s.t_cs_μ0)
    p2 = draw!(f[2, 1], d * c * s.Δt_μ0)
    pμ = draw!(f[1:2, 2], d * s.μ)
    legend!(f[0, :], p1; tellwidth=false, orientation=:horizontal)
    lines!(pμ[1].axis, [-1, 1], [-1, 1]; color=:red, linestyle=:dash)
    lines!(pμ[1].axis, [-1, 1], [1, -1]; color=:blue, linestyle=:dash)
end
easy_save("Δt")
```

```{julia}
using Statistics

errorbar_visual = (visual(ScatterLines) + visual(Errorbars; whiskerwidth=6))

begin
    β = 60
    df = @subset result :β .== β :t1 .< DEFAULT_TSPAN[2]
    # Calculate average values by binning μ0
    avg_df = @chain df begin
        @groupby(:μ0)
        @combine(:Δs_perp = mean(:Δs_perp) ± std(:Δs_perp), :Δs_para = mean(:Δs_para) ± std(:Δs_para))
        sort!(:μ0)
    end

    spec = (data(df) * visual(Scatter; markersize=5) + data(avg_df) * errorbar_visual * visual(color=:red))
    draw(spec * mapping(m.μ0, [m.Δs_para, m.Δs_perp], row=dims(1) => renamer(["", ""])))
    easy_save("Δs_β=$β")
end
```


```{julia}
using Measurements
import Base: typemax, typemin
using AlgebraOfGraphics: AesX, AesY, AesColor, Normal, dictionary
import AlgebraOfGraphics: aesthetic_mapping

typemax(::Type{Measurement{T}}) where T = typemax(T)
typemin(::Type{Measurement{T}}) where T = typemin(T)

aesthetic_mapping(::Type{Errorbars}, ::Normal, ::Normal) = errorbar_mapping(2)

function errorbar_mapping(i::Int)
    dictionary([
        1 => AesX,
        2 => AesY,
        :color => AesColor,
    ])
end
```


```{julia}

avg_df = @chain result begin
    @subset :t1 .< DEFAULT_TSPAN[2]
    @groupby(:μ0, :β)
    @combine(
        :Δs_perp = mean(:Δs_perp) ± std(:Δs_perp),
        :Δs_para = mean(:Δs_para) ± std(:Δs_para)
    )
    sort!(:μ0)
end

spec = data(avg_df) * (; group=:β => nonnumeric, color=:β => nonnumeric) * errorbar_visual
fg = draw(spec * mapping(m.μ0, [m.Δs_para, m.Δs_perp], row=dims(1) => renamer(["", ""])))
easy_save("Δs_βscan")
```

```{julia}
f = Figure()
let df = @subset result :β .== 60 :t1 .< 100
    d = data(df) * mapping(color=m.μ0_n)
    draw!(f[1, 1], d * s.s_perp)
    draw!(f[2, 1], d * s.s_para)
end
easy_save("s_perp_para")
```

```{julia}
using Statistics

begin
    tdf = @subset result :β .== 60
    df = mapreduce(vcat, [10000, 1000, 100]) do s_fs
        @chain tdf begin
            process_free_stream!(s_fs)
            @groupby(:μ0, :s_fs)
            combine([:κ_perp, :κ_para] .=> mean; renamecols=false)
            @transform! :κ_ratio = :κ_perp ./ :κ_para
            sort!(:μ0)
        end
    end
    d = data(df) * mapping(:μ0) * s.κs * visual(ScatterLines)
    axis = (; yscale=log10)
    draw(d * mapping(color=:s_fs => nonnumeric); axis)
    easy_save("κ_s_free_stream")
end
```

## Unperturbed trajectory

Note that unperturbed trajectory is different from the unscattered trajectory!!!

```{julia}
function run_upperturbed(df)
    @chain df begin
        @transform! :u1_0 = solve_unperturbed.(:B, :u0, :t1; diffeq)
        @rtransform!(:Δx = :u1[1] - :u0[1], :Δy = :u1[2] - :u0[2], :Δz = :u1[3] - :u0[3])
        @rtransform!(:lx = :u1_0[1] - :u0[1], :ly = :u1_0[2] - :u0[2], :lz = :u1_0[3] - :u0[3])
        @rtransform!(:δx = :Δx - :lx, :δy = :Δy - :ly, :δz = :Δz - :lz)
    end
end

function solve_unperturbed(B, u0, t1; save_everystep=false, alg=Vern9(), kw...)
    Bc = ConstField(B(u0))
    tspan = Float64.((0, t1))
    sol0 = solve_param(Bc, u0, tspan; save_everystep, alg, kw...)
    return sol0.u[end]
end
```


```{julia}
using LinearAlgebra
para_dist(p, p0, û) = dot(p - p0, normalize(û))

save_everystep = false
@chain result begin
    @rtransform! @astable begin
        :gc0 = guiding_center(:u0, :B)
        :gcf = guiding_center(:u1, :B)
        :Bz0 = :B(:gc0)[3]
        :s = abs(:v * :μ0 * :t1)
        sgn = sign(:Bz0 * :gc0[3])
        tspan = (0, -sgn * :s)
        fl = solve_fl(:gc0, :B; tspan, save_everystep)
        :u1_fl = fl.u[end]
        :û = :B(:u1_fl)
        # :para_dist = para_dist(:gcf, :gc0, :û)
    end
end
```


```{julia}
orig_f(x) = x[3] > 0 ? "up" : "down"
spec0 = data(results[1]) * AlgebraOfGraphics.density()
spec = spec0 * mapping(col=:u0 => orig_f)
legend = (; position=:top)
f = Figure()

p1 = draw!(f[1, 1], spec * mapping([:δx, :Δx, :lx], color=dims(1) => renamer(["δr (Δr - l_r)", "Δr", "l_r"])))
p2 = draw!(f[2, 1], spec * mapping([:δy, :Δy, :ly], color=dims(1)))
p3 = draw!(f[3, 1], spec * mapping([:δz, :Δz, :lz], color=dims(1)))
p4 = draw!(f[1:3, 2], spec0 * mapping(:Δμ, color=:u0 => orig_f))
legend!(f[0, 1], p1; tellwidth=false)
legend!(f[0, 2], p4; tellwidth=false)
f
```

```{julia}
using Statistics
f = Figure()
color = :β => nonnumeric
row = :u0 => orig_f
col = dims(1) => renamer(["", "", ""])
facet = (; linkyaxes=:none)
spec = data(result) * AlgebraOfGraphics.density(; npoints=800)
p1 = draw!(f[1, 1], spec * mapping([:δx, :δy, :δz]; col, color); facet)
p4 = draw!(f[2, 1], spec * mapping([:δx, :δy, :δz]; col, color, row); facet)
xlims!(p1[1].axis, 0, 150)
xlims!(p1[2].axis, -67, 67)
xlims!(p1[3].axis, -67, 67)
xlims!.(getaxis(p4[:, 1]), 0, 150)
xlims!.(getaxis(p4[:, 2]), -67, 67)
xlims!.(getaxis(p4[:, 3]), -67, 67)
legend!(f[0, :], p1; tellwidth=false, orientation=:horizontal)
easy_save("δr_βscan")
```